target("khr-dfd")
    set_kind("headeronly")
    add_includedirs("dfd/include", {public = true})
    add_headerfiles("dfd/include/KHR/*.h")

target("khr-dfdutils")
    set_kind("static")
    add_deps("khr-dfd")
    add_defines("LIBKTX")
    add_includedirs("dfdutils", {public = true})
    add_headerfiles("dfdutils/dfd.h")
    add_files("dfdutils/queries.c")
    add_files("dfdutils/interpretdfd.c")
    add_files("dfdutils/vk2dfd.c")
    add_files("dfdutils/createdfd.c")
    add_files("dfdutils/colourspaces.c")

target("ktx")
    set_kind("static")
    add_deps("khr-dfd")
    add_deps("khr-dfdutils")
    add_defines("LIBKTX", "KHRONOS_STATIC")
    add_includedirs("ktx/include", {public = true})
    add_headerfiles("ktx/include/*.h")
    add_includedirs("ktx/other_include", {public = false})
    add_headerfiles("ktx/other_include/KHR/*.h")
    add_includedirs("ktx/lib/basisu/zstd")
    add_files("ktx/lib/texture.c")
    add_files("ktx/lib/texture1.c")
    add_files("ktx/lib/texture2.c")
    add_files("ktx/lib/hashlist.c")
    add_files("ktx/lib/swap.c")
    add_files("ktx/lib/memstream.c")
    add_files("ktx/lib/filestream.c")
    add_files("ktx/lib/checkheader.c")
    add_files("ktx/lib/basisu/zstd/zstd.c")
    add_files("ktx/lib/miniz_wrapper.cpp")
    add_files("ktx/lib/vkformat_check.c")
    add_files("ktx/lib/vkformat_typesize.c")
